# Generated by Django 5.0.7 on 2024-07-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_bookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
    ]
